"use client";
import { useState } from "react";
import type { StudioProject,StudioSong } from "@hungreegoat/studio-contracts";
import { useSession } from "@/hooks/use-session";
import { domain,splitTags } from "@/lib/domain-client";
import { Button } from "@hungreegoat/studio-ui/components/button";
import { Input } from "@hungreegoat/studio-ui/components/input";
import { Textarea } from "@hungreegoat/studio-ui/components/textarea";
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from "@hungreegoat/studio-ui/components/select";
import { Label } from "@hungreegoat/studio-ui/components/label";
export function ProjectForm({project,onSaved}:{project?:StudioProject;onSaved:(project:StudioProject)=>void}){
 const {session}=useSession();const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
 async function submit(event:React.SubmitEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);setError(null);try{onSaved(await domain.saveProject(project?.id??null,{name:String(data.get("name")),description:String(data.get("description")),tags:splitTags(data.get("tags"))},session?.csrf_token??null));}catch(error){setError(error instanceof Error?error.message:"Project could not be saved.");}finally{setBusy(false);}}
 return <form className="space-y-4" onSubmit={submit}><div className="space-y-2"><Label htmlFor="project-name">Project name</Label><Input id="project-name" name="name" defaultValue={project?.name} maxLength={120} required /></div><div className="space-y-2"><Label htmlFor="project-description">Description</Label><Textarea id="project-description" name="description" defaultValue={project?.description} rows={3}/></div><div className="space-y-2"><Label htmlFor="project-tags">Project tags</Label><Input id="project-tags" name="tags" defaultValue={project?.tags.join(", ")} placeholder="Comma-separated tags" /></div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button type="submit" disabled={busy}>{busy?"Saving…":project?"Save project":"Create project"}</Button></form>;
}
export function SongForm({song,project,onSaved}:{song?:StudioSong;project:string;onSaved:(song:StudioSong)=>void}){
 const {session}=useSession();const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
 async function submit(event:React.SubmitEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);setError(null);try{onSaved(await domain.saveSong(song?.id??null,project,{title:String(data.get("title")),brief:String(data.get("brief")),style:String(data.get("style")),vocal_mode:String(data.get("vocal_mode")) as StudioSong["vocal_mode"],target_duration_seconds:data.get("target_duration_seconds")?Number(data.get("target_duration_seconds")):null,notes:String(data.get("notes")),tags:splitTags(data.get("tags")),bpm:data.get("bpm")?Number(data.get("bpm")):null,musical_key:String(data.get("musical_key")??"")||null},session?.csrf_token??null));}catch(error){setError(error instanceof Error?error.message:"Song could not be saved.");}finally{setBusy(false);}}
 return <form className="grid gap-5 sm:grid-cols-2" onSubmit={submit}><div className="space-y-2 sm:col-span-2"><Label htmlFor="song-title">Song title</Label><Input id="song-title" name="title" defaultValue={song?.title} maxLength={120} required /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="song-idea">The idea</Label><Textarea id="song-idea" name="brief" defaultValue={song?.brief} rows={4} placeholder="Describe the mood, style, instrumentation, and vocal direction."/></div><div className="space-y-2"><Label htmlFor="song-style">Style / genre</Label><Input id="song-style" name="style" defaultValue={song?.style} maxLength={200}/></div><div className="space-y-2"><Label htmlFor="song-vocals">Vocals</Label><Select name="vocal_mode" defaultValue={song?.vocal_mode??"auto"} items={{auto:"Open to either",instrumental:"Instrumental",vocals:"With vocals"}}><SelectTrigger id="song-vocals" className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="auto">Open to either</SelectItem><SelectItem value="instrumental">Instrumental</SelectItem><SelectItem value="vocals">With vocals</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label htmlFor="song-duration">Target duration (seconds)</Label><Input id="song-duration" name="target_duration_seconds" type="number" min={3} max={600} defaultValue={song?.target_duration_seconds??""}/></div><div className="space-y-2"><Label htmlFor="song-bpm">Target BPM</Label><Input id="song-bpm" name="bpm" type="number" min={30} max={300} defaultValue={song?.bpm??""}/></div><div className="space-y-2"><Label htmlFor="song-key">Musical key</Label><Input id="song-key" name="musical_key" defaultValue={song?.musical_key??""}/></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="song-tags">Song tags</Label><Input id="song-tags" name="tags" defaultValue={song?.tags.join(", ")} placeholder="Comma-separated tags"/></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="song-notes">Notes & references</Label><Textarea id="song-notes" name="notes" defaultValue={song?.notes} rows={3}/></div>{error&&<p role="alert" className="text-sm text-destructive sm:col-span-2">{error}</p>}<div className="sm:col-span-2"><Button type="submit" disabled={busy}>{busy?"Saving…":song?"Save song":"Create song"}</Button></div></form>;
}
