"use client";
import { useState } from "react";
import { domain } from "@/lib/domain-client";
import { useResource } from "@/hooks/use-resource";
import { PageHeading } from "@/components/page-primitives";
import { AssetList } from "@/components/domain/assets";
import { ResourceError } from "@/components/domain/project-pages";
import { Button } from "@hungreegoat/studio-ui/components/button";
import { Label } from "@hungreegoat/studio-ui/components/label";
import { Input } from "@hungreegoat/studio-ui/components/input";
import { Skeleton } from "@hungreegoat/studio-ui/components/skeleton";
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from "@hungreegoat/studio-ui/components/select";
export function LibraryPage(){const [offset,setOffset]=useState(0);const [project,setProject]=useState("");const [song,setSong]=useState("");const [query,setQuery]=useState("");const projects=useResource("library-projects",()=>domain.projects());const songs=useResource(`library-songs:${project}`,()=>project?domain.songs(project):Promise.resolve({items:[]}));const assets=useResource(`library:${project}:${song}:${offset}`,()=>domain.assets(project||undefined,song||undefined,offset));return <><PageHeading title="Library" description="Every source, every version, every finished master. Always connected to its history."/><div className="mb-6 grid gap-4 md:grid-cols-3"><div className="space-y-2"><Label htmlFor="library-project">Filter by project</Label><Select value={project} onValueChange={value=>{setProject(value??"");setSong("");setOffset(0);}} items={{"":"All projects",...Object.fromEntries(projects.data?.items.map(item=>[item.id,item.name])??[])}}><SelectTrigger id="library-project" className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="">All projects</SelectItem>{projects.data?.items.map(item=><SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="library-song">Filter by song</Label><Select value={song} onValueChange={value=>{setSong(value??"");setOffset(0);}} disabled={!project} items={{"":"All songs",...Object.fromEntries(songs.data?.items.map(item=>[item.id,item.title])??[])}}><SelectTrigger id="library-song" className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="">All songs</SelectItem>{songs.data?.items.map(item=><SelectItem key={item.id} value={item.id}>{item.title}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="library-search">Search audio</Label><Input id="library-search" placeholder="Filename" value={query} onChange={event=>setQuery(event.target.value)}/></div></div>{assets.error?<ResourceError message={assets.error} retry={assets.reload}/>:assets.data?<AssetList assets={assets.data.items.filter(item=>item.original_filename.toLowerCase().includes(query.toLowerCase()))}/>:<Skeleton className="h-48 w-full"/>}{assets.data&&<div className="mt-6 flex items-center justify-between gap-3"><Button variant="outline" disabled={offset===0} onClick={()=>setOffset(value=>Math.max(0,value-100))}>Previous assets</Button><span className="text-xs text-muted-foreground">Page {Math.floor(offset/100)+1}</span><Button variant="outline" disabled={assets.data.items.length<100} onClick={()=>setOffset(value=>value+100)}>More assets</Button></div>}</>;}
