"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { FolderOpen,Plus,Music2 } from "lucide-react";
import { domain } from "@/lib/domain-client";
import { useResource } from "@/hooks/use-resource";
import { PageHeading,EmptyPanel } from "@/components/page-primitives";
import { JobActivity } from "@/components/job-activity";
import { ProjectForm } from "@/components/domain/forms";
import { AssetUpload,AssetList } from "@/components/domain/assets";
import { Button } from "@hungreegoat/studio-ui/components/button";
import { Input } from "@hungreegoat/studio-ui/components/input";
import { Card,CardHeader,CardTitle,CardDescription,CardContent } from "@hungreegoat/studio-ui/components/card";
import { Dialog,DialogTrigger,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@hungreegoat/studio-ui/components/dialog";
import { Badge } from "@hungreegoat/studio-ui/components/badge";
import { Skeleton } from "@hungreegoat/studio-ui/components/skeleton";
export function ResourceError({message,retry}:{message:string;retry:()=>void}){return <div role="alert" className="my-5 flex flex-wrap items-center gap-3 rounded-lg border p-4"><p className="text-sm text-destructive">{message}</p><Button variant="outline" onClick={retry}>Retry</Button></div>;}
export function ProjectsPage(){const router=useRouter();const [query,setQuery]=useState("");const [offset,setOffset]=useState(0);const [open,setOpen]=useState(false);const resource=useResource(`projects:${query}:${offset}`,()=>domain.projects(query,offset));return <><PageHeading title="Projects" description="A home for every idea, from a rough sketch to a finished release."><Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button/>}><Plus/> New project</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create a project</DialogTitle><DialogDescription>Keep your songs, sources, and versions together.</DialogDescription></DialogHeader><ProjectForm onSaved={project=>{setOpen(false);router.push(`/projects/${project.id}`);}}/></DialogContent></Dialog></PageHeading><Input aria-label="Search projects" placeholder="Search projects" value={query} onChange={event=>{setQuery(event.target.value);setOffset(0);}} className="mb-6 max-w-sm"/>{resource.error?<ResourceError message={resource.error} retry={resource.reload}/>:!resource.data?<Skeleton className="h-48 w-full"/>:resource.data.items.length===0?<EmptyPanel icon={FolderOpen} title={query?"No matching projects":"A clean slate for your next idea"} description={query?"Try another project name.":"Create a project to begin collecting your songs and sounds."}/>:<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{resource.data.items.map(project=><Card key={project.id}><CardHeader><FolderOpen className="mb-2 size-5 text-amber-700"/><CardTitle><Link className="break-words hover:underline" href={`/projects/${project.id}`}>{project.name}</Link></CardTitle><CardDescription className="line-clamp-3 whitespace-pre-wrap">{project.description||"A fresh space for your sound."}</CardDescription></CardHeader><CardContent><div className="flex flex-wrap gap-2">{project.tags.map(tag=><Badge key={tag} variant="secondary">{tag}</Badge>)}</div></CardContent></Card>)}</div>}{resource.data&&<div className="mt-6 flex items-center justify-between gap-3"><Button variant="outline" disabled={offset===0} onClick={()=>setOffset(value=>Math.max(0,value-100))}>Previous projects</Button><span className="text-xs text-muted-foreground">Page {Math.floor(offset/100)+1}</span><Button variant="outline" disabled={resource.data.items.length<100} onClick={()=>setOffset(value=>value+100)}>More projects</Button></div>}</>;}
export function ProjectDetail({id}:{id:string}){const [edit,setEdit]=useState(false);const project=useResource(`project:${id}`,()=>domain.project(id));const songs=useResource(`songs:${id}`,()=>domain.songs(id));const assets=useResource(`assets:${id}`,()=>domain.assets(id));if(project.error)return <ResourceError message={project.error} retry={project.reload}/>;if(!project.data)return <Skeleton className="h-56 w-full"/>;const item=project.data;return <><PageHeading eyebrow="PROJECT" title={item.name} description={item.description||"Your songs and sources, together."}><div className="flex gap-2"><Dialog open={edit} onOpenChange={setEdit}><DialogTrigger render={<Button variant="outline"/>}>Edit project</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Edit project</DialogTitle><DialogDescription>Changes are saved to your workspace.</DialogDescription></DialogHeader><ProjectForm project={item} onSaved={()=>{setEdit(false);void project.reload();}}/></DialogContent></Dialog><Button render={<Link href={`/songs/new?project_id=${id}`}/>} nativeButton={false}><Plus/> New song</Button></div></PageHeading><div className="mb-6 flex flex-wrap gap-2">{item.tags.map(tag=><Badge key={tag} variant="secondary">{tag}</Badge>)}</div><section className="mb-8 space-y-4"><h2 className="text-xl font-semibold">Songs</h2>{songs.error?<ResourceError message={songs.error} retry={songs.reload}/>:!songs.data?<Skeleton className="h-24 w-full"/>:songs.data.items.length===0?<EmptyPanel icon={Music2} title="Give this project its first song" description="A brief and a few musical anchors are enough to begin." href={`/songs/new?project_id=${id}`} action="Create a song"/>:<div className="grid gap-4 md:grid-cols-2">{songs.data.items.map(song=><Card key={song.id}><CardHeader><CardTitle><Link href={`/songs/${song.id}`} className="break-words hover:underline">{song.title}</Link></CardTitle><CardDescription>{song.bpm?`${song.bpm} BPM` : "Tempo open"} · {song.musical_key??"Key open"}</CardDescription></CardHeader></Card>)}</div>}</section><div className="mb-8"><JobActivity project={id}/></div><section className="space-y-5"><h2 className="text-xl font-semibold">Project audio</h2><AssetUpload project={id} song={null} onUploaded={()=>void assets.reload()}/>{assets.error?<ResourceError message={assets.error} retry={assets.reload}/>:assets.data?<AssetList assets={assets.data.items}/>:<Skeleton className="h-24 w-full"/>}</section></>;}
