"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { domain } from "@/lib/domain-client";
import { useResource } from "@/hooks/use-resource";
import { useSongContext } from "@/hooks/use-song-context";
import { SongForm } from "@/components/domain/forms";
import { AssetUpload,AssetList } from "@/components/domain/assets";
import { ResourceError } from "@/components/domain/project-pages";
import { PageHeading } from "@/components/page-primitives";
import { Button } from "@hungreegoat/studio-ui/components/button";
import { Card,CardHeader,CardTitle,CardDescription,CardContent } from "@hungreegoat/studio-ui/components/card";
import { Label } from "@hungreegoat/studio-ui/components/label";
import { Badge } from "@hungreegoat/studio-ui/components/badge";
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from "@hungreegoat/studio-ui/components/select";
import { Dialog,DialogTrigger,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@hungreegoat/studio-ui/components/dialog";
import { Skeleton } from "@hungreegoat/studio-ui/components/skeleton";
import { navigation } from "@/lib/navigation";
export function NewSongPage(){const router=useRouter();const {select}=useSongContext();const projects=useResource("projects:new-song",()=>domain.projects());const [project,setProject]=useState<string|null>(()=>typeof window!=="undefined"?new URLSearchParams(window.location.search).get("project_id"):null);return <><PageHeading title="New song" description="Start with a feeling, a reference, or a half-formed idea. The details can evolve."/><Card><CardHeader><CardTitle>The starting point</CardTitle><CardDescription>Your brief is saved with the project, ready to refine.</CardDescription></CardHeader><CardContent className="space-y-6">{projects.error?<ResourceError message={projects.error} retry={projects.reload}/>:!projects.data?<Skeleton className="h-24 w-full"/>:projects.data.items.length===0?<div className="space-y-4"><p className="text-sm text-muted-foreground">Create a project first to give this song a home.</p><Button render={<Link href="/projects"/>} nativeButton={false}>Create a project</Button></div>:<><div className="max-w-lg space-y-2"><Label htmlFor="song-project">Project</Label><Select value={project} onValueChange={setProject} items={Object.fromEntries(projects.data.items.map(item=>[item.id,item.name]))}><SelectTrigger id="song-project" className="w-full"><SelectValue placeholder="Choose a project"/></SelectTrigger><SelectContent>{projects.data.items.map(item=><SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div>{project?<SongForm project={project} onSaved={song=>{select(song);router.push(`/songs/${song.id}`);}}/>:<p className="text-sm text-muted-foreground">Choose a project to start your brief.</p>}</>}</CardContent></Card></>;}
export function SongDetail({id}:{id:string}){const {select}=useSongContext();const [edit,setEdit]=useState(false);const song=useResource(`song:${id}`,()=>domain.song(id));const assets=useResource(`song-assets:${id}`,()=>domain.assets(undefined,id));useEffect(()=>{if(song.data)select(song.data);},[song.data,select]);if(song.error)return <ResourceError message={song.error} retry={song.reload}/>;if(!song.data)return <Skeleton className="h-56 w-full"/>;const item=song.data;return <><PageHeading eyebrow="SONG" title={item.title} description={item.brief||"A new idea, ready to take shape."}><Dialog open={edit} onOpenChange={setEdit}><DialogTrigger render={<Button variant="outline"/>}>Edit song</DialogTrigger><DialogContent className="max-h-[90svh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Edit song</DialogTitle><DialogDescription>Update the direction without changing any audio.</DialogDescription></DialogHeader><SongForm song={item} project={item.project_id} onSaved={next=>{select(next);setEdit(false);void song.reload();}}/></DialogContent></Dialog></PageHeading><div className="mb-6 flex flex-wrap items-center gap-2"><Badge variant="secondary">{item.bpm?`${item.bpm} BPM`:"Tempo open"}</Badge><Badge variant="secondary">{item.musical_key??"Key open"}</Badge>{item.style&&<Badge variant="secondary">{item.style}</Badge>}<Badge variant="secondary">{item.vocal_mode === "auto" ? "Open to either" : item.vocal_mode === "vocals" ? "With vocals" : "Instrumental"}</Badge>{item.target_duration_seconds&&<Badge variant="secondary">{item.target_duration_seconds} sec target</Badge>}{item.tags.map(tag=><Badge key={tag} variant="outline">{tag}</Badge>)}<Link href={`/projects/${item.project_id}`} className="text-xs underline underline-offset-4">View project</Link></div>{item.notes&&<Card className="mb-6"><CardHeader><CardTitle className="text-sm">Notes & references</CardTitle></CardHeader><CardContent className="whitespace-pre-wrap text-sm text-muted-foreground">{item.notes}</CardContent></Card>}<div className="mb-8 flex flex-wrap gap-2">{navigation.filter(item=>["Create","Shape","Finish"].includes(item.group)&&item.href!=="/library").map(({href,label,icon:Icon})=><Button key={href} variant="outline" size="sm" render={<Link href={`${href}?song_id=${id}`}/>} nativeButton={false}><Icon/>{label}</Button>)}</div><section className="space-y-5"><h2 className="text-xl font-semibold">Audio & version history</h2><AssetUpload project={item.project_id} song={id} onUploaded={()=>void assets.reload()}/>{assets.error?<ResourceError message={assets.error} retry={assets.reload}/>:assets.data?<AssetList assets={assets.data.items}/>:<Skeleton className="h-24 w-full"/>}</section></>;}
