import Link from "next/link";
import { Plus, ArrowRight, Music2, AudioLines, Disc3, Sparkles } from "lucide-react";
import { Button } from "@hungreegoat/studio-ui/components/button";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@hungreegoat/studio-ui/components/card";
import { PageHeading } from "@/components/page-primitives";
import { JobActivity } from "@/components/job-activity";
import { DashboardProjects } from "@/components/domain/dashboard-projects";
import { HealthStatus } from "@/components/health-status";
export default function Dashboard() {
  return <><PageHeading eyebrow="A LITTLE SPACE. A LOT OF POSSIBILITY." title="Welcome to your studio" description="Pick up where inspiration left off, or start something entirely new."><Button render={<Link href="/songs/new" />} nativeButton={false}><Plus /> New song</Button></PageHeading><div className="mb-8 grid gap-4 sm:grid-cols-3">{[{ label: "Projects", icon: Music2, hint: "Your ideas, organized" }, { label: "Active jobs", icon: AudioLines, hint: "Production in motion" }, { label: "Final masters", icon: Disc3, hint: "Ready for the world" }].map(({ label, icon: Icon, hint }) => <Card key={label}><CardHeader className="flex-row items-center justify-between"><CardTitle className="text-sm font-medium text-muted-foreground">{label}</CardTitle><Icon className="size-4 text-muted-foreground" /></CardHeader><CardContent><p className="text-3xl font-semibold">—</p><p className="mt-2 text-xs text-muted-foreground">{hint}</p></CardContent></Card>)}</div><div className="grid gap-6 xl:grid-cols-[minmax(0,1.7fr)_minmax(0,1fr)]"><section className="space-y-4"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Recent projects</h2><Link href="/projects" className="flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground">View all <ArrowRight className="size-3" /></Link></div><DashboardProjects /></section><section className="space-y-4"><h2 className="text-lg font-semibold">A spark to get you started</h2><Card className="bg-accent/40"><CardHeader><Sparkles className="mb-3 size-6 text-amber-800" /><CardTitle>Give your idea a direction.</CardTitle><CardDescription className="leading-relaxed">Describe the feeling, the energy, the sound in your head. Your AI Producer helps shape it into a plan.</CardDescription></CardHeader><CardContent><Button variant="outline" render={<Link href="/producer" />} nativeButton={false}>Explore AI Producer <ArrowRight /></Button></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Studio connection</CardTitle></CardHeader><CardContent><HealthStatus /></CardContent></Card></section></div><div className="mt-8"><JobActivity title="Active & recent jobs" compact /></div></>;
}
