"use client";
import Link from "next/link";
import { useState } from "react";
import { useSongContext } from "@/hooks/use-song-context";
import { useSession } from "@/hooks/use-session";
import { usePathname } from "next/navigation";
import { AudioLines, Plus, ChevronDown, Music2 } from "lucide-react";
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarGroup, SidebarGroupLabel, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarFooter, SidebarTrigger, useSidebar } from "@hungreegoat/studio-ui/components/sidebar";
import { Button } from "@hungreegoat/studio-ui/components/button";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuGroup, DropdownMenuItem, DropdownMenuSeparator } from "@hungreegoat/studio-ui/components/dropdown-menu";
import { navigation } from "@/lib/navigation";
function Navigation() {
  const pathname = usePathname();
  const { setOpenMobile } = useSidebar();
  const {toolHref}=useSongContext();
  return <Sidebar collapsible="offcanvas"><SidebarHeader className="gap-6 p-5"><Link href="/" className="flex items-center gap-3" aria-label="Hungree Goat Studio home"><span className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><AudioLines /></span><span><span className="block text-sm font-bold tracking-tight">HUNGREE GOAT</span><span className="block text-[10px] tracking-widest text-muted-foreground">AI MUSIC STUDIO</span></span></Link><Button render={<Link href="/songs/new" />} nativeButton={false} onClick={() => setOpenMobile(false)}><Plus /> New song</Button></SidebarHeader><SidebarContent><nav aria-label="Studio navigation">{["Workspace", "Create", "Shape", "Finish", "Workspace settings"].map(group => <SidebarGroup key={group} className="px-3 py-1"><SidebarGroupLabel className="text-[10px] uppercase tracking-widest">{group}</SidebarGroupLabel><SidebarMenu>{navigation.filter(item => item.group === group).map(({ href, label, icon: Icon }) => <SidebarMenuItem key={href}><SidebarMenuButton render={<Link href={["/","/projects","/settings","/library"].includes(href)?href:toolHref(href)} />} isActive={pathname === href} aria-current={pathname === href ? "page" : undefined} className="h-9 gap-3 px-3" onClick={() => setOpenMobile(false)}><Icon /><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup>)}</nav></SidebarContent><SidebarFooter className="border-t p-5"><p className="text-xs font-medium">Your independent workspace</p><p className="text-[11px] text-muted-foreground">Ideas in. Music out.</p></SidebarFooter></Sidebar>;
}
export function StudioShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const {song,clear,error:selectionError}=useSongContext();
  const { session, logout } = useSession(); const [logoutError,setLogoutError] = useState<string|null>(null);
  async function signOut() { try { await logout(); } catch(error) { setLogoutError(error instanceof Error ? error.message : "Sign out failed."); } }
  return <SidebarProvider><Navigation /><div className="flex min-w-0 flex-1 flex-col"><a href="#studio-content" className="sr-only focus:not-sr-only focus:p-3">Skip to content</a><header className="flex flex-wrap items-center justify-between gap-3 border-b bg-card px-4 py-4 md:px-8"><div className="flex min-w-0 items-center gap-3"><SidebarTrigger aria-label="Toggle navigation" /><span className="max-w-40 truncate text-sm text-muted-foreground">{session?.workspaces.find(item => item.id === session.active_workspace_id)?.name ?? "Workspace"}</span><span className="text-border">/</span><span className="truncate text-sm font-medium">{pathname === "/songs/new" ? "New song" : navigation.find(item => item.href === pathname)?.label ?? "Studio"}</span></div><DropdownMenu><DropdownMenuTrigger render={<Button variant="outline" size="sm" />}><Music2 /><span className="max-w-44 truncate">{song?.title??"No song selected"}</span><ChevronDown /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuGroup><DropdownMenuLabel>Current project & song</DropdownMenuLabel>{song&&<><DropdownMenuItem render={<Link href={`/songs/${song.id}`}/>}>Open current song</DropdownMenuItem><DropdownMenuItem onClick={clear}>Clear song selection</DropdownMenuItem></>}<DropdownMenuSeparator /><DropdownMenuItem render={<Link href="/projects" />}>Choose a project</DropdownMenuItem><DropdownMenuItem render={<Link href="/songs/new" />}>Start a new song</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onClick={() => void signOut()}>Sign out</DropdownMenuItem></DropdownMenuGroup></DropdownMenuContent></DropdownMenu></header>{selectionError && <p role="alert" className="px-8 py-3 text-sm text-destructive">{selectionError}</p>}{logoutError && <p role="alert" className="px-8 py-3 text-sm text-destructive">{logoutError}</p>}<main id="studio-content" className="mx-auto w-full max-w-[1600px] flex-1 p-4 md:p-8 lg:p-10">{children}</main><footer className="flex flex-wrap items-center justify-between gap-3 border-t px-4 py-4 text-xs text-muted-foreground md:px-8"><span className="flex items-center gap-2"><AudioLines className="size-4" /> Select an audio version to begin listening</span><span>Non-destructive by design</span></footer></div></SidebarProvider>;
}
