"use client";
import Link from "next/link";
import { Music2, AudioLines, Sparkles } from "lucide-react";
import { Button } from "@hungreegoat/studio-ui/components/button";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@hungreegoat/studio-ui/components/card";
import { Badge } from "@hungreegoat/studio-ui/components/badge";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@hungreegoat/studio-ui/components/tabs";
import { JobActivity } from "@/components/job-activity";
import { useSongContext } from "@/hooks/use-song-context";
import { PageHeading, EmptyPanel } from "@/components/page-primitives";
export const workstationPages = {
  producer: { title: "AI Producer", description: "Turn the sound in your head into a thoughtful production plan.", tabs: ["Creative brief", "Production plan"], empty: "Your vision, with a little direction", detail: "Choose a song and connect an AI provider to develop your brief into instrumentation, structure, and delivery notes.", side: "Production direction", fields: ["Mood & energy", "Instrumentation", "Structure", "Avoid"] },
  generation: { title: "Generation", description: "Explore musical possibilities. Keep the versions that move you.", tabs: ["Versions", "Generation history"], empty: "Make room for your first version", detail: "A production plan and a connected music provider are needed to create music. Each generation becomes an immutable version.", side: "Generation settings", fields: ["Music provider", "Model", "Duration", "Version count"] },
  compare: { title: "Listen & Compare", description: "Listen closely, leave notes, and find the version worth taking further.", tabs: ["A/B comparison", "Review notes"], empty: "Two versions. One fresh perspective.", detail: "Select generated versions to compare their waveforms, switch playback, and choose your preferred take.", side: "Version details", fields: ["Duration", "Tempo", "Key", "Review status"] },
  arrangement: { title: "Arrangement", description: "Shape the journey of your track, one section at a time.", tabs: ["Timeline", "Revision history"], empty: "Give your song its shape", detail: "Choose an approved version to map sections, set energy, and save a new arrangement revision.", side: "Section inspector", fields: ["Selected section", "Instrumentation", "Energy", "Instructions"] },
  tempo: { title: "Tempo / Remix", description: "Explore a new pace and perspective while keeping your original intact.", tabs: ["Tempo & pitch", "Transform history"], empty: "Find a different groove", detail: "Choose an audio version to analyze tempo, preview a new BPM, or create a pitch-shifted variation.", side: "Transform settings", fields: ["Detected BPM", "Target BPM", "Pitch shift", "Preserve pitch"] },
  stems: { title: "Stems & Mixing", description: "Hear the individual parts. Bring them together your way.", tabs: ["Stem mixer", "Stem sets"], empty: "Get closer to every layer", detail: "Select an audio version to separate vocals, drums, bass, and other instruments into a new stem set.", side: "Mix details", fields: ["Source version", "Stem model", "Output format", "Mix revision"] },
  mastering: { title: "Mastering", description: "Bring your mix into focus and prepare it for the world.", tabs: ["Mastering workspace", "Master versions"], empty: "The finishing touch starts with a mix", detail: "Select your mix and a reference track to create a new master. Compare before and after without changing the source.", side: "Mastering setup", fields: ["Source mix", "Reference track", "Output format", "Master version"] },
} as const;
export function Workstation({ page }: { page: keyof typeof workstationPages }) {
  const config = workstationPages[page];
  const {song}=useSongContext();
  return <><PageHeading eyebrow="CREATE • SHAPE • FINISH" title={config.title} description={config.description}><Badge variant="outline">{song?.title??"No song selected"}</Badge></PageHeading><Tabs defaultValue="workspace"><TabsList className="mb-6 max-w-full overflow-x-auto"><TabsTrigger value="workspace">{config.tabs[0]}</TabsTrigger><TabsTrigger value="history">{config.tabs[1]}</TabsTrigger></TabsList><TabsContent value="workspace"><div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_19rem]"><EmptyPanel icon={page === "producer" ? Sparkles : AudioLines} title={config.empty} description={song?`“${song.title}” is selected. This production tool will become available when its processing workflow is connected.`:config.detail} href={song?`/songs/${song.id}`:"/songs/new"} action={song?"Open song & audio":"Start with a song"} /><Card><CardHeader><CardTitle>{config.side}</CardTitle><CardDescription>Available when a source is selected.</CardDescription></CardHeader><CardContent className="space-y-5">{config.fields.map(field => <div key={field} className="flex items-center justify-between gap-4 border-b pb-3 text-sm"><span className="text-muted-foreground">{field}</span><span aria-label={`${field} not selected`}>—</span></div>)}<Button variant="outline" className="w-full" render={<Link href="/projects" />} nativeButton={false}>Choose a project</Button></CardContent></Card></div>{song && <div className="mt-6"><JobActivity song={song.id}/></div>}</TabsContent><TabsContent value="history"><EmptyPanel icon={Music2} title="A fresh page in your song’s story" description="Saved versions and decisions will appear here when you begin working on a song." href="/projects" action="Browse projects" /></TabsContent></Tabs></>;
}
