"use client";
import Link from "next/link";
import { Music2, AudioLines, Plus, FolderOpen, Search, SlidersHorizontal, Sparkles } from "lucide-react";
import { Button } from "@hungreegoat/studio-ui/components/button";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@hungreegoat/studio-ui/components/card";
import { Badge } from "@hungreegoat/studio-ui/components/badge";
import { Input } from "@hungreegoat/studio-ui/components/input";
import { Textarea } from "@hungreegoat/studio-ui/components/textarea";
import { Label } from "@hungreegoat/studio-ui/components/label";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@hungreegoat/studio-ui/components/tabs";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@hungreegoat/studio-ui/components/select";
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@hungreegoat/studio-ui/components/table";
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter, DialogClose } from "@hungreegoat/studio-ui/components/dialog";
import { Progress } from "@hungreegoat/studio-ui/components/progress";
import { PageHeading, EmptyPanel } from "@/components/page-primitives";
export const workstationPages = {
  producer: { title: "AI Producer", description: "Turn the sound in your head into a thoughtful production plan.", tabs: ["Creative brief", "Production plan"], empty: "Your vision, with a little direction", detail: "Choose a song and connect an AI provider to develop your brief into instrumentation, structure, and delivery notes.", side: "Production direction", fields: ["Mood & energy", "Instrumentation", "Structure", "Avoid"] },
  generation: { title: "Generation", description: "Explore musical possibilities. Keep the versions that move you.", tabs: ["Versions", "Generation history"], empty: "Make room for your first version", detail: "A production plan and a connected music provider are needed to create music. Each generation becomes an immutable version.", side: "Generation settings", fields: ["Music provider", "Model", "Duration", "Version count"] },
  compare: { title: "Listen & Compare", description: "Listen closely, leave notes, and find the version worth taking further.", tabs: ["A/B comparison", "Review notes"], empty: "Two versions. One fresh perspective.", detail: "Select generated versions to compare their waveforms, switch playback, and choose your preferred take.", side: "Version details", fields: ["Duration", "Tempo", "Key", "Review status"] },
  arrangement: { title: "Arrangement", description: "Shape the journey of your track, one section at a time.", tabs: ["Timeline", "Revision history"], empty: "Give your song its shape", detail: "Choose an approved version to map sections, set energy, and save a new arrangement revision.", side: "Section inspector", fields: ["Selected section", "Instrumentation", "Energy", "Instructions"] },
  tempo: { title: "Tempo / Remix", description: "Explore a new pace and perspective while keeping your original intact.", tabs: ["Tempo & pitch", "Transform history"], empty: "Find a different groove", detail: "Choose an audio version to analyze tempo, preview a new BPM, or create a pitch-shifted variation.", side: "Transform settings", fields: ["Detected BPM", "Target BPM", "Pitch shift", "Preserve pitch"] },
  stems: { title: "Stems & Mixing", description: "Hear the individual parts. Bring them together your way.", tabs: ["Stem mixer", "Stem sets"], empty: "Get closer to every layer", detail: "Select an audio version to separate vocals, drums, bass, and other instruments into a new stem set.", side: "Mix details", fields: ["Source version", "Stem model", "Output format", "Mix revision"] },
  mastering: { title: "Mastering", description: "Bring your mix into focus and prepare it for the world.", tabs: ["Mastering workspace", "Master versions"], empty: "The finishing touch starts with a mix", detail: "Select your mix and a reference track to create a new master. Compare before and after without changing the source.", side: "Mastering setup", fields: ["Source mix", "Reference track", "Output format", "Master version"] },
} as const;
export function Workstation({ page }: { page: keyof typeof workstationPages }) {
  const config = workstationPages[page];
  return <><PageHeading eyebrow="CREATE • SHAPE • FINISH" title={config.title} description={config.description}><Badge variant="outline">No song selected</Badge></PageHeading><Tabs defaultValue="workspace"><TabsList className="mb-6 max-w-full overflow-x-auto"><TabsTrigger value="workspace">{config.tabs[0]}</TabsTrigger><TabsTrigger value="history">{config.tabs[1]}</TabsTrigger></TabsList><TabsContent value="workspace"><div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_19rem]"><EmptyPanel icon={page === "producer" ? Sparkles : AudioLines} title={config.empty} description={config.detail} href="/songs/new" action="Start with a song" /><Card><CardHeader><CardTitle>{config.side}</CardTitle><CardDescription>Available when a source is selected.</CardDescription></CardHeader><CardContent className="space-y-5">{config.fields.map(field => <div key={field} className="flex items-center justify-between gap-4 border-b pb-3 text-sm"><span className="text-muted-foreground">{field}</span><span aria-label={`${field} not selected`}>—</span></div>)}<Button variant="outline" className="w-full" render={<Link href="/projects" />} nativeButton={false}>Choose a project</Button></CardContent></Card></div>{page === "generation" && <Card className="mt-6"><CardHeader><CardTitle className="text-sm">Job activity</CardTitle><CardDescription>No generation is running. Progress will appear here and recover after refresh.</CardDescription></CardHeader><CardContent><Progress value={0} aria-label="Generation progress" /></CardContent></Card>}</TabsContent><TabsContent value="history"><EmptyPanel icon={Music2} title="A fresh page in your song’s story" description="Saved versions and decisions will appear here when you begin working on a song." href="/projects" action="Browse projects" /></TabsContent></Tabs></>;
}
export function Projects() {
 return <><PageHeading title="Projects" description="A home for every idea, from a rough sketch to a finished release."><Dialog><DialogTrigger render={<Button />}><Plus /> New project</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create a project</DialogTitle><DialogDescription>Project storage is being prepared. Explore the song brief to gather your first idea.</DialogDescription></DialogHeader><DialogFooter><DialogClose render={<Button variant="outline" />}>Close</DialogClose><Button render={<Link href="/songs/new" />} nativeButton={false}>Explore song brief</Button></DialogFooter></DialogContent></Dialog></PageHeading><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div className="flex w-full max-w-sm items-center gap-2 rounded-lg border bg-card px-3"><Search className="size-4 text-muted-foreground" /><Input aria-label="Search projects" placeholder="Search projects" className="border-0 shadow-none" /></div><Badge variant="secondary">Workspace ready for your ideas</Badge></div><EmptyPanel icon={FolderOpen} title="A clean slate for your next idea" description="Projects keep songs, production plans, audio versions, and exports together. Begin with a song brief to set the direction." href="/songs/new" action="Start a song brief" /></>;
}
export function NewSong() {
 return <><PageHeading title="New song" description="Start with a feeling, a reference, or a half-formed idea. The details can evolve." /><div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_19rem]"><Card><CardHeader><CardTitle>The starting point</CardTitle><CardDescription>Sketch your brief. Saving becomes available when project storage is connected.</CardDescription></CardHeader><CardContent><form className="grid gap-5 sm:grid-cols-2" onSubmit={event => event.preventDefault()}><div className="space-y-2 sm:col-span-2"><Label htmlFor="song-title">Song title</Label><Input id="song-title" placeholder="Give your idea a name" maxLength={200} /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="song-idea">The idea</Label><Textarea id="song-idea" placeholder="What should this song feel like?" rows={4} /></div><div className="space-y-2"><Label htmlFor="song-style">Style / genre</Label><Input id="song-style" placeholder="Warm, soulful house" /></div><div className="space-y-2"><Label htmlFor="song-bpm">Target BPM</Label><Input id="song-bpm" type="number" min={30} max={300} placeholder="120" /></div><div className="space-y-2"><Label htmlFor="song-key">Musical key (optional)</Label><Input id="song-key" placeholder="A minor" /></div><div className="space-y-2"><Label htmlFor="song-vocals">Vocals</Label><Select defaultValue="instrumental" items={{ instrumental: "Instrumental", vocals: "With vocals", either: "Open to either" }}><SelectTrigger id="song-vocals" className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="instrumental">Instrumental</SelectItem><SelectItem value="vocals">With vocals</SelectItem><SelectItem value="either">Open to either</SelectItem></SelectContent></Select></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="song-notes">Notes & references</Label><Textarea id="song-notes" placeholder="Anything else that matters to your sound" rows={3} /></div><p className="text-xs leading-relaxed text-muted-foreground sm:col-span-2" role="status">This brief is not saved yet. Project persistence is not connected.</p></form></CardContent></Card><Card className="bg-accent/30"><CardHeader><Sparkles className="mb-3 size-6 text-amber-800" /><CardTitle>Leave room for surprise.</CardTitle><CardDescription className="leading-relaxed">A clear mood and a few musical anchors can be enough. You can refine instrumentation, structure, and energy with your AI Producer.</CardDescription></CardHeader><CardContent><Button variant="outline" render={<Link href="/producer" />} nativeButton={false}>Explore AI Producer</Button></CardContent></Card></div></>;
}
export function Library() {
 return <><PageHeading title="Library" description="Every source, every version, every finished master. Always connected to its history." /><Tabs defaultValue="all"><TabsList className="mb-6 max-w-full overflow-x-auto">{["All assets", "Versions", "Stems", "Masters", "Exports"].map((tab,index) => <TabsTrigger value={index === 0 ? "all" : tab} key={tab}>{tab}</TabsTrigger>)}</TabsList>{["all", "Versions", "Stems", "Masters", "Exports"].map(tab => <TabsContent value={tab} key={tab}><Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-4"><CardTitle>{tab === "all" ? "All assets" : tab}</CardTitle><div className="flex items-center gap-2"><SlidersHorizontal className="size-4 text-muted-foreground" /><Input aria-label={`Search ${tab}`} placeholder="Search your library" /></div></div></CardHeader><CardContent><Table><TableHeader><TableRow>{["Name", "Type", "Source", "Created"].map(header => <TableHead key={header}>{header}</TableHead>)}</TableRow></TableHeader><TableBody><TableRow><TableCell colSpan={4} className="whitespace-normal py-16 text-center text-muted-foreground">Your {tab === "all" ? "audio assets" : tab.toLowerCase()} will appear here as you create.</TableCell></TableRow></TableBody></Table></CardContent></Card></TabsContent>)}</Tabs></>;
}
