"use client";
import { KeyRound, AudioLines, HardDrive, SlidersHorizontal, Download, Users, Palette, HeartPulse, ExternalLink } from "lucide-react";
import { useSettings } from "@/hooks/use-settings";
import { SettingsForm, PasswordForm } from "@/components/settings-form";
import { Skeleton } from "@hungreegoat/studio-ui/components/skeleton";
import { PageHeading } from "@/components/page-primitives";
import { HealthStatus } from "@/components/health-status";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@hungreegoat/studio-ui/components/card";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@hungreegoat/studio-ui/components/tabs";
import { Badge } from "@hungreegoat/studio-ui/components/badge";
import { Button } from "@hungreegoat/studio-ui/components/button";
import { ProviderSettings } from "@/components/provider-settings";
const categories = [{ name: "Providers", icon: KeyRound }, { name: "Audio engines", icon: AudioLines }, { name: "Storage", icon: HardDrive }, { name: "Audio defaults", icon: SlidersHorizontal }, { name: "Export defaults", icon: Download }, { name: "Workspace", icon: Users }, { name: "Appearance", icon: Palette }, { name: "Health", icon: HeartPulse }];
export default function Settings() {
 const {settings,system,error,saving,reload,save}=useSettings();
 return <><PageHeading title="Settings" description="Make this workspace yours. Connect the tools that help you create." />{error && <div role="alert" className="mb-6 flex flex-wrap items-center gap-3 text-sm text-destructive">{error}<Button variant="outline" onClick={()=>void reload()}>Retry settings</Button></div>}<Tabs defaultValue="Providers"><TabsList variant="line" className="mb-8 h-auto w-full flex-wrap justify-start gap-2 group-data-[orientation=horizontal]/tabs:h-auto">{categories.map(({ name, icon: Icon }) => <TabsTrigger key={name} value={name} className="h-auto flex-none gap-2 px-3 py-2"><Icon className="size-4" />{name}</TabsTrigger>)}</TabsList><TabsContent value="Providers"><ProviderSettings settings={settings} save={save} saving={saving} reloadSettings={reload} /></TabsContent>{categories.filter(c => c.name !== "Providers").map(({ name, icon: Icon }) => <TabsContent key={name} value={name}><Card><CardHeader><Icon className="mb-3 size-6 text-amber-800" /><CardTitle>{name}</CardTitle><CardDescription>{name === "Health" ? "Check the connection between your browser and the Studio control plane." : name === "Appearance" ? "A calm, light workspace with warm neutrals and restrained gold accents." : `Your ${name.toLowerCase()} configuration will be managed here.`}</CardDescription></CardHeader><CardContent>{name === "Health" ? <HealthStatus /> : name === "Audio engines" ? <div className="space-y-4"><p className="text-xs text-muted-foreground">Availability on this Studio server. Worker capabilities may differ.</p>{system?.engines.map(engine=><div key={engine.id} className="flex items-center justify-between gap-4 rounded-lg border p-4"><span>{engine.name}</span><Badge variant="outline">{engine.available ? "Available" : "Not installed"}</Badge></div>)}</div> : name === "Storage" ? <div className="space-y-3"><p>{system?.storage.available ? "Asset storage available" : "Asset storage unavailable"}</p>{system?.storage.free_bytes != null && <p className="text-sm text-muted-foreground">{(system.storage.free_bytes / 1024 ** 3).toFixed(1)} GB free of {((system.storage.total_bytes ?? 0) / 1024 ** 3).toFixed(1)} GB</p>}</div> : !settings ? <Skeleton className="h-24 w-full" aria-label="Loading settings" /> : <><SettingsForm key={name} section={name === "Workspace" ? "workspace" : name === "Appearance" ? "appearance" : name === "Audio defaults" ? "audio" : "exports"} settings={settings} save={save} saving={saving} />{name === "Workspace" && <PasswordForm />}</>}</CardContent></Card></TabsContent>)}</Tabs><p className="mt-8 flex items-center gap-2 text-xs text-muted-foreground"><ExternalLink className="size-3" /> Provider capabilities and usage depend on your connected account.</p></>;
}
