"""core domain and immutable assets"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0004_domain"
down_revision = "0003_provider_configs"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=4000), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(trim(name)) > 0", name="project_nonempty_name"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id"),
    )
    op.create_index(op.f("ix_projects_workspace_id"), "projects", ["workspace_id"], unique=False)
    op.create_table(
        "songs",
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("brief", sa.String(length=8000), nullable=False),
        sa.Column("notes", sa.String(length=16000), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("bpm", sa.Integer(), nullable=True),
        sa.Column("musical_key", sa.String(length=32), nullable=True),
        sa.Column("style", sa.String(length=1000), nullable=False),
        sa.Column("vocal_mode", sa.String(length=16), nullable=False),
        sa.Column("target_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "vocal_mode IN ('instrumental','vocals','auto')", name="song_vocal_mode"
        ),
        sa.CheckConstraint("bpm IS NULL OR (bpm >= 30 AND bpm <= 300)", name="song_bpm_range"),
        sa.CheckConstraint("length(trim(title)) > 0", name="song_nonempty_title"),
        sa.CheckConstraint(
            "target_duration_seconds IS NULL OR "
            "(target_duration_seconds >= 3 AND target_duration_seconds <= 600)",
            name="song_target_duration",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "project_id", "workspace_id"),
    )
    op.create_index(op.f("ix_songs_project_id"), "songs", ["project_id"], unique=False)
    op.create_index(op.f("ix_songs_workspace_id"), "songs", ["workspace_id"], unique=False)
    op.create_table(
        "audio_assets",
        sa.Column("song_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("original_filename", sa.String(length=180), nullable=False),
        sa.Column("media_type", sa.String(length=80), nullable=False),
        sa.Column("storage_key", sa.String(length=80), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("channels", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "byte_size > 0 AND duration_seconds > 0 AND sample_rate > 0 AND channels > 0",
            name="asset_positive_media",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id", "project_id", "workspace_id"],
            ["songs.id", "songs.project_id", "songs.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "project_id", "workspace_id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_audio_assets_project_id"), "audio_assets", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_audio_assets_sha256"), "audio_assets", ["sha256"], unique=False)
    op.create_index(
        op.f("ix_audio_assets_workspace_id"), "audio_assets", ["workspace_id"], unique=False
    )
    op.create_table(
        "production_plans",
        sa.Column("song_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("version > 0", name="plan_version_positive"),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id", "project_id", "workspace_id"],
            ["songs.id", "songs.project_id", "songs.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "project_id", "workspace_id"),
        sa.UniqueConstraint("song_id", "version"),
        sa.UniqueConstraint("id", "song_id", "project_id", "workspace_id"),
    )
    op.create_index(
        "uq_production_plan_active",
        "production_plans",
        ["song_id"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_index(
        op.f("ix_production_plans_project_id"), "production_plans", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_production_plans_workspace_id"), "production_plans", ["workspace_id"], unique=False
    )
    op.create_table(
        "asset_lineage",
        sa.Column("parent_asset_id", sa.Uuid(), nullable=False),
        sa.Column("child_asset_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("parent_asset_id <> child_asset_id", name="lineage_not_self"),
        sa.ForeignKeyConstraint(
            ["child_asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_asset_id", "child_asset_id", "operation"),
    )
    op.create_index(
        op.f("ix_asset_lineage_project_id"), "asset_lineage", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_asset_lineage_workspace_id"), "asset_lineage", ["workspace_id"], unique=False
    )
    op.create_table(
        "audio_analysis",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("analyzer_version", sa.String(length=64), nullable=False),
        sa.Column("detected_bpm", sa.Float(), nullable=True),
        sa.Column("musical_key", sa.String(length=32), nullable=True),
        sa.Column("measurements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "analyzer_version"),
    )
    op.create_index(
        op.f("ix_audio_analysis_project_id"), "audio_analysis", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_audio_analysis_workspace_id"), "audio_analysis", ["workspace_id"], unique=False
    )
    op.create_table(
        "exports",
        sa.Column("source_asset_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("format IN ('wav','mp3','zip')", name="export_valid_format"),
        sa.ForeignKeyConstraint(
            ["asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id"),
    )
    op.create_index(op.f("ix_exports_project_id"), "exports", ["project_id"], unique=False)
    op.create_index(op.f("ix_exports_workspace_id"), "exports", ["workspace_id"], unique=False)
    op.create_table(
        "generations",
        sa.Column("song_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id", "song_id", "project_id", "workspace_id"],
            [
                "production_plans.id",
                "production_plans.song_id",
                "production_plans.project_id",
                "production_plans.workspace_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id", "project_id", "workspace_id"],
            ["songs.id", "songs.project_id", "songs.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "project_id", "workspace_id"),
    )
    op.create_index(op.f("ix_generations_project_id"), "generations", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_generations_workspace_id"), "generations", ["workspace_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("song_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("current_stage", sa.String(length=120), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("result_asset_id", sa.Uuid(), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "state IN ('pending','queued','running','succeeded','failed','cancelled')",
            name="job_valid_state",
        ),
        sa.CheckConstraint(
            "progress_percent >= 0 AND progress_percent <= 100", name="job_progress_range"
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["result_asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id", "project_id", "workspace_id"],
            ["songs.id", "songs.project_id", "songs.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "project_id", "workspace_id"),
    )
    op.create_index(op.f("ix_jobs_project_id"), "jobs", ["project_id"], unique=False)
    op.create_index(op.f("ix_jobs_workspace_id"), "jobs", ["workspace_id"], unique=False)
    op.create_table(
        "masters",
        sa.Column("source_asset_id", sa.Uuid(), nullable=False),
        sa.Column("reference_asset_id", sa.Uuid(), nullable=True),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("engine", sa.String(length=64), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["reference_asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id"),
    )
    op.create_index(op.f("ix_masters_project_id"), "masters", ["project_id"], unique=False)
    op.create_index(op.f("ix_masters_workspace_id"), "masters", ["workspace_id"], unique=False)
    op.create_table(
        "stem_sets",
        sa.Column("source_asset_id", sa.Uuid(), nullable=False),
        sa.Column("engine", sa.String(length=64), nullable=False),
        sa.Column("engine_version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "project_id", "workspace_id"),
    )
    op.create_index(op.f("ix_stem_sets_project_id"), "stem_sets", ["project_id"], unique=False)
    op.create_index(op.f("ix_stem_sets_workspace_id"), "stem_sets", ["workspace_id"], unique=False)
    op.create_table(
        "tempo_versions",
        sa.Column("source_asset_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("ratio", sa.Float(), nullable=False),
        sa.Column("pitch_semitones", sa.Float(), nullable=False),
        sa.Column("preserve_pitch", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("ratio > 0", name="tempo_positive_ratio"),
        sa.ForeignKeyConstraint(
            ["asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id"),
    )
    op.create_index(
        op.f("ix_tempo_versions_project_id"), "tempo_versions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_tempo_versions_workspace_id"), "tempo_versions", ["workspace_id"], unique=False
    )
    op.create_table(
        "generation_versions",
        sa.Column("generation_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.String(length=8000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("version > 0", name="generation_version_positive"),
        sa.ForeignKeyConstraint(
            ["asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["generation_id", "project_id", "workspace_id"],
            ["generations.id", "generations.project_id", "generations.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("generation_id", "version"),
        sa.UniqueConstraint("id", "project_id", "workspace_id"),
    )
    op.create_index(
        op.f("ix_generation_versions_project_id"),
        "generation_versions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_versions_workspace_id"),
        "generation_versions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "job_events",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id", "project_id", "workspace_id"],
            ["jobs.id", "jobs.project_id", "jobs.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "sequence"),
    )
    op.create_index(op.f("ix_job_events_project_id"), "job_events", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_job_events_workspace_id"), "job_events", ["workspace_id"], unique=False
    )
    op.create_table(
        "mix_versions",
        sa.Column("stem_set_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("levels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("version > 0", name="mix_version_positive"),
        sa.ForeignKeyConstraint(
            ["asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["stem_set_id", "project_id", "workspace_id"],
            ["stem_sets.id", "stem_sets.project_id", "stem_sets.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stem_set_id", "version"),
    )
    op.create_index(
        op.f("ix_mix_versions_project_id"), "mix_versions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_mix_versions_workspace_id"), "mix_versions", ["workspace_id"], unique=False
    )
    op.create_table(
        "stems",
        sa.Column("stem_set_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["stem_set_id", "project_id", "workspace_id"],
            ["stem_sets.id", "stem_sets.project_id", "stem_sets.workspace_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stem_set_id", "label"),
    )
    op.create_index(op.f("ix_stems_project_id"), "stems", ["project_id"], unique=False)
    op.create_index(op.f("ix_stems_workspace_id"), "stems", ["workspace_id"], unique=False)
    op.create_table(
        "arrangements",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("revision > 0", name="arrangement_revision_positive"),
        sa.ForeignKeyConstraint(
            ["asset_id", "project_id", "workspace_id"],
            ["audio_assets.id", "audio_assets.project_id", "audio_assets.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "workspace_id"],
            ["projects.id", "projects.workspace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id", "project_id", "workspace_id"],
            [
                "generation_versions.id",
                "generation_versions.project_id",
                "generation_versions.workspace_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "revision"),
    )
    op.create_index(
        op.f("ix_arrangements_project_id"), "arrangements", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_arrangements_workspace_id"), "arrangements", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_arrangements_workspace_id"), table_name="arrangements")
    op.drop_index(op.f("ix_arrangements_project_id"), table_name="arrangements")
    op.drop_table("arrangements")
    op.drop_index(op.f("ix_stems_workspace_id"), table_name="stems")
    op.drop_index(op.f("ix_stems_project_id"), table_name="stems")
    op.drop_table("stems")
    op.drop_index(op.f("ix_mix_versions_workspace_id"), table_name="mix_versions")
    op.drop_index(op.f("ix_mix_versions_project_id"), table_name="mix_versions")
    op.drop_table("mix_versions")
    op.drop_index(op.f("ix_job_events_workspace_id"), table_name="job_events")
    op.drop_index(op.f("ix_job_events_project_id"), table_name="job_events")
    op.drop_table("job_events")
    op.drop_index(op.f("ix_generation_versions_workspace_id"), table_name="generation_versions")
    op.drop_index(op.f("ix_generation_versions_project_id"), table_name="generation_versions")
    op.drop_table("generation_versions")
    op.drop_index(op.f("ix_tempo_versions_workspace_id"), table_name="tempo_versions")
    op.drop_index(op.f("ix_tempo_versions_project_id"), table_name="tempo_versions")
    op.drop_table("tempo_versions")
    op.drop_index(op.f("ix_stem_sets_workspace_id"), table_name="stem_sets")
    op.drop_index(op.f("ix_stem_sets_project_id"), table_name="stem_sets")
    op.drop_table("stem_sets")
    op.drop_index(op.f("ix_masters_workspace_id"), table_name="masters")
    op.drop_index(op.f("ix_masters_project_id"), table_name="masters")
    op.drop_table("masters")
    op.drop_index(op.f("ix_jobs_workspace_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_project_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_generations_workspace_id"), table_name="generations")
    op.drop_index(op.f("ix_generations_project_id"), table_name="generations")
    op.drop_table("generations")
    op.drop_index(op.f("ix_exports_workspace_id"), table_name="exports")
    op.drop_index(op.f("ix_exports_project_id"), table_name="exports")
    op.drop_table("exports")
    op.drop_index(op.f("ix_audio_analysis_workspace_id"), table_name="audio_analysis")
    op.drop_index(op.f("ix_audio_analysis_project_id"), table_name="audio_analysis")
    op.drop_table("audio_analysis")
    op.drop_index(op.f("ix_asset_lineage_workspace_id"), table_name="asset_lineage")
    op.drop_index(op.f("ix_asset_lineage_project_id"), table_name="asset_lineage")
    op.drop_table("asset_lineage")
    op.drop_index(op.f("ix_production_plans_workspace_id"), table_name="production_plans")
    op.drop_index(op.f("ix_production_plans_project_id"), table_name="production_plans")
    op.drop_table("production_plans")
    op.drop_index(op.f("ix_audio_assets_workspace_id"), table_name="audio_assets")
    op.drop_index(op.f("ix_audio_assets_sha256"), table_name="audio_assets")
    op.drop_index(op.f("ix_audio_assets_project_id"), table_name="audio_assets")
    op.drop_table("audio_assets")
    op.drop_index(op.f("ix_songs_workspace_id"), table_name="songs")
    op.drop_index(op.f("ix_songs_project_id"), table_name="songs")
    op.drop_table("songs")
    op.drop_index(op.f("ix_projects_workspace_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
